title = "Gitleaks custom configuration"

[[rules]]
id = "hardcoded-generic-password"
description = "Detects hardcoded passwords assigned to a variable."
# This simplified regex matches 'password = ' followed by anything in quotes.
# We use .* to match any sequence of characters.
regex = '''password\s*=\s*['"].*['"]'''
tags = ["password", "hardcoded"]
