name: Credential Detection TruffleHog
on:
  push:
    branches: [ main, develop, 'feature/**' ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          BASE="origin/${{ github.base_ref }}"
        else
          BASE="${{ github.event.before }}"
        fi
        
        # For the very first commit, scan all files
        if [ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]; then
          CHANGED_FILES=$(git ls-files | tr '\n' ' ')
          echo "First commit detected - scanning all files."
        else
          CHANGED_FILES=$(git diff --name-only $BASE...HEAD | tr '\n' ' ')
        fi

        if [ -z "$CHANGED_FILES" ]; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "No files changed, skipping scan."
        else
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "changed_files=$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "Files to scan: $CHANGED_FILES"
        fi

    - name: Run TruffleHog
      id: trufflehog
      if: steps.changed-files.outputs.has_changes == 'true'
      run: |
        # Install TruffleHog
        curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
        
        CHANGED_FILES="${{ steps.changed-files.outputs.changed_files }}"
        
        # --- FIX ---
        # Changed --exclude to the correct flag: --exclude-paths
        trufflehog filesystem $CHANGED_FILES --json --no-verification --exclude-paths .github/workflows/ > trufflehog_results.json || true
        
        # Check if the results file has content (i.e., if secrets were found)
        if [ -s trufflehog_results.json ]; then
          echo "secrets_found=true" >> $GITHUB_OUTPUT
        else
          echo "secrets_found=false" >> $GITHUB_OUTPUT
        fi

    - name: Parse and display results
      if: steps.trufflehog.outputs.secrets_found == 'true'
      run: |
        echo "========================================"
        echo "🚨 CREDENTIAL DETECTION RESULTS"
        echo "========================================"
        # Use jq for simpler, more reliable parsing.
        jq -r '"❌ Found \(.DetectorName) in file: \(.SourceMetadata.Data.Filesystem.file)"' trufflehog_results.json
        
    - name: Fail if secrets found
      if: steps.trufflehog.outputs.secrets_found == 'true'
      run: |
        echo ""
        echo "❌ ACTION FAILED: Secrets detected in repository."
        echo "💡 Please remove all exposed credentials before merging."
        exit 1
        
    - name: Success message
      if: steps.changed-files.outputs.has_changes == 'true' && steps.trufflehog.outputs.secrets_found == 'false'
      run: |
        echo "✅ SUCCESS: No secrets detected in changed files!"

    - name: No changes message
      if: steps.changed-files.outputs.has_changes == 'false'
      run: |
        echo "ℹ️ No files changed - skipping credential scan."
