name: Credentials Detection

on: [push, pull_request]

jobs:
  scan:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch the full history to be able to compare commits
          fetch-depth: 0

      - name: List changed files
        run: |
          # Set the base and head commits for comparison
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BASE_COMMIT="${{ github.event.pull_request.base.sha }}"
            HEAD_COMMIT="${{ github.event.pull_request.head.sha }}"
          else
            BASE_COMMIT="${{ github.event.before }}"
            HEAD_COMMIT="${{ github.event.after }}"
          fi

          echo "Base commit is: $BASE_COMMIT"
          echo "Head commit is: $HEAD_COMMIT"

          # List the files that will be scanned
          echo "Files being scanned:"
          git diff --name-only $BASE_COMMIT $HEAD_COMMIT

      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITLEAKS_PAT }}
        with:
          # This option tells Gitleaks to scan a specific range of commits.
          # It's the key to scanning only the changes in the PR/commit.
          log_opts: "--all -- ${GITLEAKS_PATTERNS_PATH:-.}"
          # The following is a more modern approach but might not work in all event types
          # log_opts: ${{ github.event.before }}..${{ github.event.after }}

      - name: Upload Gitleaks report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
